services:
  app:
    build: .
    container_name: gerenciador-livros
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    stdin_open: true
    tty: true
    command: node app.js
 
